# name: CI

# on:
#   push:
#     branches: [ "main" ]

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - name: Install Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18

#       - name: Install dependencies
#         run: npm install

#       - name: Run ESLint
#         run: npx eslint index.js






# name: CI

# on:
#   push:
#     branches: ["main"]

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Install Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 18

#       - name: Install dependencies
#         run: npm install --legacy-peer-deps

#       - name: Run ESLint
#         run: npx eslint . || true






name: CI

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run ESLint
        run: npx eslint . || true

      # 👉 SONAR FIX COMPLET
      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=jmseraphin_Smarthotel
            -Dsonar.organization=jmseraphin
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**